/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Block
 */
export interface Block {
    /**
     * 
     * @type {number}
     * @memberof Block
     */
    workchainId: number;
    /**
     * 
     * @type {string}
     * @memberof Block
     */
    shard: string;
    /**
     * 
     * @type {number}
     * @memberof Block
     */
    seqno: number;
    /**
     * 
     * @type {string}
     * @memberof Block
     */
    rootHash: string;
    /**
     * 
     * @type {string}
     * @memberof Block
     */
    fileHash: string;
    /**
     * 
     * @type {number}
     * @memberof Block
     */
    globalId: number;
    /**
     * 
     * @type {number}
     * @memberof Block
     */
    version: number;
    /**
     * 
     * @type {boolean}
     * @memberof Block
     */
    afterMerge: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Block
     */
    beforeSplit: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Block
     */
    afterSplit: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Block
     */
    wantSplit: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Block
     */
    wantMerge: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Block
     */
    keyBlock: boolean;
    /**
     * 
     * @type {number}
     * @memberof Block
     */
    genUtime: number;
    /**
     * 
     * @type {number}
     * @memberof Block
     */
    startLt: number;
    /**
     * 
     * @type {number}
     * @memberof Block
     */
    endLt: number;
    /**
     * 
     * @type {number}
     * @memberof Block
     */
    vertSeqno: number;
    /**
     * 
     * @type {number}
     * @memberof Block
     */
    genCatchainSeqno: number;
    /**
     * 
     * @type {number}
     * @memberof Block
     */
    minRefMcSeqno: number;
    /**
     * 
     * @type {number}
     * @memberof Block
     */
    prevKeyBlockSeqno: number;
    /**
     * 
     * @type {number}
     * @memberof Block
     */
    genSoftwareVersion?: number;
    /**
     * 
     * @type {number}
     * @memberof Block
     */
    genSoftwareCapabilities?: number;
    /**
     * 
     * @type {string}
     * @memberof Block
     */
    masterRef?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Block
     */
    prevRefs: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof Block
     */
    inMsgDescrLength: number;
    /**
     * 
     * @type {number}
     * @memberof Block
     */
    outMsgDescrLength: number;
    /**
     * 
     * @type {string}
     * @memberof Block
     */
    randSeed: string;
    /**
     * 
     * @type {string}
     * @memberof Block
     */
    createdBy: string;
}

/**
 * Check if a given object implements the Block interface.
 */
export function instanceOfBlock(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "workchainId" in value;
    isInstance = isInstance && "shard" in value;
    isInstance = isInstance && "seqno" in value;
    isInstance = isInstance && "rootHash" in value;
    isInstance = isInstance && "fileHash" in value;
    isInstance = isInstance && "globalId" in value;
    isInstance = isInstance && "version" in value;
    isInstance = isInstance && "afterMerge" in value;
    isInstance = isInstance && "beforeSplit" in value;
    isInstance = isInstance && "afterSplit" in value;
    isInstance = isInstance && "wantSplit" in value;
    isInstance = isInstance && "wantMerge" in value;
    isInstance = isInstance && "keyBlock" in value;
    isInstance = isInstance && "genUtime" in value;
    isInstance = isInstance && "startLt" in value;
    isInstance = isInstance && "endLt" in value;
    isInstance = isInstance && "vertSeqno" in value;
    isInstance = isInstance && "genCatchainSeqno" in value;
    isInstance = isInstance && "minRefMcSeqno" in value;
    isInstance = isInstance && "prevKeyBlockSeqno" in value;
    isInstance = isInstance && "prevRefs" in value;
    isInstance = isInstance && "inMsgDescrLength" in value;
    isInstance = isInstance && "outMsgDescrLength" in value;
    isInstance = isInstance && "randSeed" in value;
    isInstance = isInstance && "createdBy" in value;

    return isInstance;
}

export function BlockFromJSON(json: any): Block {
    return BlockFromJSONTyped(json, false);
}

export function BlockFromJSONTyped(json: any, ignoreDiscriminator: boolean): Block {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'workchainId': json['workchain_id'],
        'shard': json['shard'],
        'seqno': json['seqno'],
        'rootHash': json['root_hash'],
        'fileHash': json['file_hash'],
        'globalId': json['global_id'],
        'version': json['version'],
        'afterMerge': json['after_merge'],
        'beforeSplit': json['before_split'],
        'afterSplit': json['after_split'],
        'wantSplit': json['want_split'],
        'wantMerge': json['want_merge'],
        'keyBlock': json['key_block'],
        'genUtime': json['gen_utime'],
        'startLt': json['start_lt'],
        'endLt': json['end_lt'],
        'vertSeqno': json['vert_seqno'],
        'genCatchainSeqno': json['gen_catchain_seqno'],
        'minRefMcSeqno': json['min_ref_mc_seqno'],
        'prevKeyBlockSeqno': json['prev_key_block_seqno'],
        'genSoftwareVersion': !exists(json, 'gen_software_version') ? undefined : json['gen_software_version'],
        'genSoftwareCapabilities': !exists(json, 'gen_software_capabilities') ? undefined : json['gen_software_capabilities'],
        'masterRef': !exists(json, 'master_ref') ? undefined : json['master_ref'],
        'prevRefs': json['prev_refs'],
        'inMsgDescrLength': json['in_msg_descr_length'],
        'outMsgDescrLength': json['out_msg_descr_length'],
        'randSeed': json['rand_seed'],
        'createdBy': json['created_by'],
    };
}

export function BlockToJSON(value?: Block | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'workchain_id': value.workchainId,
        'shard': value.shard,
        'seqno': value.seqno,
        'root_hash': value.rootHash,
        'file_hash': value.fileHash,
        'global_id': value.globalId,
        'version': value.version,
        'after_merge': value.afterMerge,
        'before_split': value.beforeSplit,
        'after_split': value.afterSplit,
        'want_split': value.wantSplit,
        'want_merge': value.wantMerge,
        'key_block': value.keyBlock,
        'gen_utime': value.genUtime,
        'start_lt': value.startLt,
        'end_lt': value.endLt,
        'vert_seqno': value.vertSeqno,
        'gen_catchain_seqno': value.genCatchainSeqno,
        'min_ref_mc_seqno': value.minRefMcSeqno,
        'prev_key_block_seqno': value.prevKeyBlockSeqno,
        'gen_software_version': value.genSoftwareVersion,
        'gen_software_capabilities': value.genSoftwareCapabilities,
        'master_ref': value.masterRef,
        'prev_refs': value.prevRefs,
        'in_msg_descr_length': value.inMsgDescrLength,
        'out_msg_descr_length': value.outMsgDescrLength,
        'rand_seed': value.randSeed,
        'created_by': value.createdBy,
    };
}

