/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FoundAccountsAddressesInner
 */
export interface FoundAccountsAddressesInner {
    /**
     * 
     * @type {string}
     * @memberof FoundAccountsAddressesInner
     */
    address: string;
    /**
     * 
     * @type {string}
     * @memberof FoundAccountsAddressesInner
     */
    name: string;
}

/**
 * Check if a given object implements the FoundAccountsAddressesInner interface.
 */
export function instanceOfFoundAccountsAddressesInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "address" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function FoundAccountsAddressesInnerFromJSON(json: any): FoundAccountsAddressesInner {
    return FoundAccountsAddressesInnerFromJSONTyped(json, false);
}

export function FoundAccountsAddressesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): FoundAccountsAddressesInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'address': json['address'],
        'name': json['name'],
    };
}

export function FoundAccountsAddressesInnerToJSON(value?: FoundAccountsAddressesInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'address': value.address,
        'name': value.name,
    };
}

