/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetChartRates200Response
 */
export interface GetChartRates200Response {
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof GetChartRates200Response
     */
    points: { [key: string]: any; };
}

/**
 * Check if a given object implements the GetChartRates200Response interface.
 */
export function instanceOfGetChartRates200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "points" in value;

    return isInstance;
}

export function GetChartRates200ResponseFromJSON(json: any): GetChartRates200Response {
    return GetChartRates200ResponseFromJSONTyped(json, false);
}

export function GetChartRates200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetChartRates200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'points': json['points'],
    };
}

export function GetChartRates200ResponseToJSON(value?: GetChartRates200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'points': value.points,
    };
}

