/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@fslabs.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const JettonVerificationType = {
    Whitelist: 'whitelist',
    Blacklist: 'blacklist',
    None: 'none'
} as const;
export type JettonVerificationType = typeof JettonVerificationType[keyof typeof JettonVerificationType];


export function JettonVerificationTypeFromJSON(json: any): JettonVerificationType {
    return JettonVerificationTypeFromJSONTyped(json, false);
}

export function JettonVerificationTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): JettonVerificationType {
    return json as JettonVerificationType;
}

export function JettonVerificationTypeToJSON(value?: JettonVerificationType | null): any {
    return value as any;
}

