/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JettonMetadata
 */
export interface JettonMetadata {
    /**
     * 
     * @type {string}
     * @memberof JettonMetadata
     */
    address: string;
    /**
     * 
     * @type {string}
     * @memberof JettonMetadata
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof JettonMetadata
     */
    symbol: string;
    /**
     * 
     * @type {string}
     * @memberof JettonMetadata
     */
    decimals: string;
    /**
     * 
     * @type {string}
     * @memberof JettonMetadata
     */
    image?: string;
    /**
     * 
     * @type {string}
     * @memberof JettonMetadata
     */
    description?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof JettonMetadata
     */
    social?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof JettonMetadata
     */
    websites?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof JettonMetadata
     */
    catalogs?: Array<string>;
}

/**
 * Check if a given object implements the JettonMetadata interface.
 */
export function instanceOfJettonMetadata(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "address" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "symbol" in value;
    isInstance = isInstance && "decimals" in value;

    return isInstance;
}

export function JettonMetadataFromJSON(json: any): JettonMetadata {
    return JettonMetadataFromJSONTyped(json, false);
}

export function JettonMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): JettonMetadata {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'address': json['address'],
        'name': json['name'],
        'symbol': json['symbol'],
        'decimals': json['decimals'],
        'image': !exists(json, 'image') ? undefined : json['image'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'social': !exists(json, 'social') ? undefined : json['social'],
        'websites': !exists(json, 'websites') ? undefined : json['websites'],
        'catalogs': !exists(json, 'catalogs') ? undefined : json['catalogs'],
    };
}

export function JettonMetadataToJSON(value?: JettonMetadata | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'address': value.address,
        'name': value.name,
        'symbol': value.symbol,
        'decimals': value.decimals,
        'image': value.image,
        'description': value.description,
        'social': value.social,
        'websites': value.websites,
        'catalogs': value.catalogs,
    };
}

