/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AccountAddress } from './AccountAddress';
import {
    AccountAddressFromJSON,
    AccountAddressFromJSONTyped,
    AccountAddressToJSON,
} from './AccountAddress';

/**
 * 
 * @export
 * @interface RecoverStakeAction
 */
export interface RecoverStakeAction {
    /**
     * 
     * @type {number}
     * @memberof RecoverStakeAction
     */
    amount: number;
    /**
     * 
     * @type {AccountAddress}
     * @memberof RecoverStakeAction
     */
    staker: AccountAddress;
}

/**
 * Check if a given object implements the RecoverStakeAction interface.
 */
export function instanceOfRecoverStakeAction(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "amount" in value;
    isInstance = isInstance && "staker" in value;

    return isInstance;
}

export function RecoverStakeActionFromJSON(json: any): RecoverStakeAction {
    return RecoverStakeActionFromJSONTyped(json, false);
}

export function RecoverStakeActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecoverStakeAction {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'staker': AccountAddressFromJSON(json['staker']),
    };
}

export function RecoverStakeActionToJSON(value?: RecoverStakeAction | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'amount': value.amount,
        'staker': AccountAddressToJSON(value.staker),
    };
}

