/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Subscription } from './Subscription';
import {
    SubscriptionFromJSON,
    SubscriptionFromJSONTyped,
    SubscriptionToJSON,
} from './Subscription';

/**
 * 
 * @export
 * @interface Subscriptions
 */
export interface Subscriptions {
    /**
     * 
     * @type {Array<Subscription>}
     * @memberof Subscriptions
     */
    subscriptions: Array<Subscription>;
}

/**
 * Check if a given object implements the Subscriptions interface.
 */
export function instanceOfSubscriptions(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "subscriptions" in value;

    return isInstance;
}

export function SubscriptionsFromJSON(json: any): Subscriptions {
    return SubscriptionsFromJSONTyped(json, false);
}

export function SubscriptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Subscriptions {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'subscriptions': ((json['subscriptions'] as Array<any>).map(SubscriptionFromJSON)),
    };
}

export function SubscriptionsToJSON(value?: Subscriptions | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'subscriptions': ((value.subscriptions as Array<any>).map(SubscriptionToJSON)),
    };
}

