/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TraceId } from './TraceId';
import {
    TraceIdFromJSON,
    TraceIdFromJSONTyped,
    TraceIdToJSON,
} from './TraceId';

/**
 * 
 * @export
 * @interface TraceIds
 */
export interface TraceIds {
    /**
     * 
     * @type {Array<TraceId>}
     * @memberof TraceIds
     */
    traces: Array<TraceId>;
}

/**
 * Check if a given object implements the TraceIds interface.
 */
export function instanceOfTraceIds(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "traces" in value;

    return isInstance;
}

export function TraceIdsFromJSON(json: any): TraceIds {
    return TraceIdsFromJSONTyped(json, false);
}

export function TraceIdsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TraceIds {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'traces': ((json['traces'] as Array<any>).map(TraceIdFromJSON)),
    };
}

export function TraceIdsToJSON(value?: TraceIds | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'traces': ((value.traces as Array<any>).map(TraceIdToJSON)),
    };
}

