/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TraceId
 */
export interface TraceId {
    /**
     * 
     * @type {string}
     * @memberof TraceId
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof TraceId
     */
    utime: number;
}

/**
 * Check if a given object implements the TraceId interface.
 */
export function instanceOfTraceId(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "utime" in value;

    return isInstance;
}

export function TraceIdFromJSON(json: any): TraceId {
    return TraceIdFromJSONTyped(json, false);
}

export function TraceIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): TraceId {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'utime': json['utime'],
    };
}

export function TraceIdToJSON(value?: TraceId | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'utime': value.utime,
    };
}

