/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@fslabs.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AccountAddress } from './AccountAddress';
import {
    AccountAddressFromJSON,
    AccountAddressFromJSONTyped,
    AccountAddressToJSON,
} from './AccountAddress';

/**
 * 
 * @export
 * @interface ValueFlowNftsInner
 */
export interface ValueFlowNftsInner {
    /**
     * 
     * @type {AccountAddress}
     * @memberof ValueFlowNftsInner
     */
    account: AccountAddress;
    /**
     * 
     * @type {number}
     * @memberof ValueFlowNftsInner
     */
    quantity: number;
}

/**
 * Check if a given object implements the ValueFlowNftsInner interface.
 */
export function instanceOfValueFlowNftsInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "account" in value;
    isInstance = isInstance && "quantity" in value;

    return isInstance;
}

export function ValueFlowNftsInnerFromJSON(json: any): ValueFlowNftsInner {
    return ValueFlowNftsInnerFromJSONTyped(json, false);
}

export function ValueFlowNftsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValueFlowNftsInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'account': AccountAddressFromJSON(json['account']),
        'quantity': json['quantity'],
    };
}

export function ValueFlowNftsInnerToJSON(value?: ValueFlowNftsInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'account': AccountAddressToJSON(value.account),
        'quantity': value.quantity,
    };
}

