/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@fslabs.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ActionSimplePreview } from './ActionSimplePreview';
import {
    ActionSimplePreviewFromJSON,
    ActionSimplePreviewFromJSONTyped,
    ActionSimplePreviewToJSON,
} from './ActionSimplePreview';
import type { AuctionBidAction } from './AuctionBidAction';
import {
    AuctionBidActionFromJSON,
    AuctionBidActionFromJSONTyped,
    AuctionBidActionToJSON,
} from './AuctionBidAction';
import type { ContractDeployAction } from './ContractDeployAction';
import {
    ContractDeployActionFromJSON,
    ContractDeployActionFromJSONTyped,
    ContractDeployActionToJSON,
} from './ContractDeployAction';
import type { JettonTransferAction } from './JettonTransferAction';
import {
    JettonTransferActionFromJSON,
    JettonTransferActionFromJSONTyped,
    JettonTransferActionToJSON,
} from './JettonTransferAction';
import type { NftItemTransferAction } from './NftItemTransferAction';
import {
    NftItemTransferActionFromJSON,
    NftItemTransferActionFromJSONTyped,
    NftItemTransferActionToJSON,
} from './NftItemTransferAction';
import type { NftPurchase } from './NftPurchase';
import {
    NftPurchaseFromJSON,
    NftPurchaseFromJSONTyped,
    NftPurchaseToJSON,
} from './NftPurchase';
import type { SubscriptionAction } from './SubscriptionAction';
import {
    SubscriptionActionFromJSON,
    SubscriptionActionFromJSONTyped,
    SubscriptionActionToJSON,
} from './SubscriptionAction';
import type { TonTransferAction } from './TonTransferAction';
import {
    TonTransferActionFromJSON,
    TonTransferActionFromJSONTyped,
    TonTransferActionToJSON,
} from './TonTransferAction';
import type { UnSubscriptionAction } from './UnSubscriptionAction';
import {
    UnSubscriptionActionFromJSON,
    UnSubscriptionActionFromJSONTyped,
    UnSubscriptionActionToJSON,
} from './UnSubscriptionAction';

/**
 * 
 * @export
 * @interface Action
 */
export interface Action {
    /**
     * 
     * @type {AuctionBidAction}
     * @memberof Action
     */
    auctionBid?: AuctionBidAction;
    /**
     * 
     * @type {ContractDeployAction}
     * @memberof Action
     */
    contractDeploy?: ContractDeployAction;
    /**
     * 
     * @type {JettonTransferAction}
     * @memberof Action
     */
    jettonTransfer?: JettonTransferAction;
    /**
     * 
     * @type {NftItemTransferAction}
     * @memberof Action
     */
    nftItemTransfer?: NftItemTransferAction;
    /**
     * 
     * @type {NftPurchase}
     * @memberof Action
     */
    nftPurchase?: NftPurchase;
    /**
     * 
     * @type {SubscriptionAction}
     * @memberof Action
     */
    subscribe?: SubscriptionAction;
    /**
     * 
     * @type {TonTransferAction}
     * @memberof Action
     */
    tonTransfer?: TonTransferAction;
    /**
     * 
     * @type {UnSubscriptionAction}
     * @memberof Action
     */
    unSubscribe?: UnSubscriptionAction;
    /**
     * 
     * @type {ActionSimplePreview}
     * @memberof Action
     */
    simplePreview: ActionSimplePreview;
    /**
     * 
     * @type {string}
     * @memberof Action
     */
    status: ActionStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof Action
     */
    type: ActionTypeEnum;
}


/**
 * @export
 */
export const ActionStatusEnum = {
    Ok: 'ok',
    Failed: 'failed',
    Pending: 'pending'
} as const;
export type ActionStatusEnum = typeof ActionStatusEnum[keyof typeof ActionStatusEnum];

/**
 * @export
 */
export const ActionTypeEnum = {
    TonTransfer: 'TonTransfer',
    JettonTransfer: 'JettonTransfer',
    NftItemTransfer: 'NftItemTransfer',
    ContractDeploy: 'ContractDeploy',
    Subscribe: 'Subscribe',
    UnSubscribe: 'UnSubscribe',
    AuctionBid: 'AuctionBid',
    NftPurchase: 'NftPurchase',
    Unknown: 'Unknown'
} as const;
export type ActionTypeEnum = typeof ActionTypeEnum[keyof typeof ActionTypeEnum];


/**
 * Check if a given object implements the Action interface.
 */
export function instanceOfAction(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "simplePreview" in value;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "type" in value;

    return isInstance;
}

export function ActionFromJSON(json: any): Action {
    return ActionFromJSONTyped(json, false);
}

export function ActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Action {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'auctionBid': !exists(json, 'AuctionBid') ? undefined : AuctionBidActionFromJSON(json['AuctionBid']),
        'contractDeploy': !exists(json, 'ContractDeploy') ? undefined : ContractDeployActionFromJSON(json['ContractDeploy']),
        'jettonTransfer': !exists(json, 'JettonTransfer') ? undefined : JettonTransferActionFromJSON(json['JettonTransfer']),
        'nftItemTransfer': !exists(json, 'NftItemTransfer') ? undefined : NftItemTransferActionFromJSON(json['NftItemTransfer']),
        'nftPurchase': !exists(json, 'NftPurchase') ? undefined : NftPurchaseFromJSON(json['NftPurchase']),
        'subscribe': !exists(json, 'Subscribe') ? undefined : SubscriptionActionFromJSON(json['Subscribe']),
        'tonTransfer': !exists(json, 'TonTransfer') ? undefined : TonTransferActionFromJSON(json['TonTransfer']),
        'unSubscribe': !exists(json, 'UnSubscribe') ? undefined : UnSubscriptionActionFromJSON(json['UnSubscribe']),
        'simplePreview': ActionSimplePreviewFromJSON(json['simple_preview']),
        'status': json['status'],
        'type': json['type'],
    };
}

export function ActionToJSON(value?: Action | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'AuctionBid': AuctionBidActionToJSON(value.auctionBid),
        'ContractDeploy': ContractDeployActionToJSON(value.contractDeploy),
        'JettonTransfer': JettonTransferActionToJSON(value.jettonTransfer),
        'NftItemTransfer': NftItemTransferActionToJSON(value.nftItemTransfer),
        'NftPurchase': NftPurchaseToJSON(value.nftPurchase),
        'Subscribe': SubscriptionActionToJSON(value.subscribe),
        'TonTransfer': TonTransferActionToJSON(value.tonTransfer),
        'UnSubscribe': UnSubscriptionActionToJSON(value.unSubscribe),
        'simple_preview': ActionSimplePreviewToJSON(value.simplePreview),
        'status': value.status,
        'type': value.type,
    };
}

