/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@fslabs.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Auction } from './Auction';
import {
    AuctionFromJSON,
    AuctionFromJSONTyped,
    AuctionToJSON,
} from './Auction';

/**
 * 
 * @export
 * @interface Auctions
 */
export interface Auctions {
    /**
     * 
     * @type {Array<Auction>}
     * @memberof Auctions
     */
    data: Array<Auction>;
    /**
     * 
     * @type {number}
     * @memberof Auctions
     */
    total: number;
}

/**
 * Check if a given object implements the Auctions interface.
 */
export function instanceOfAuctions(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "total" in value;

    return isInstance;
}

export function AuctionsFromJSON(json: any): Auctions {
    return AuctionsFromJSONTyped(json, false);
}

export function AuctionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Auctions {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(AuctionFromJSON)),
        'total': json['total'],
    };
}

export function AuctionsToJSON(value?: Auctions | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(AuctionToJSON)),
        'total': value.total,
    };
}

