/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@fslabs.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Auction
 */
export interface Auction {
    /**
     * 
     * @type {number}
     * @memberof Auction
     */
    bids: number;
    /**
     * 
     * @type {number}
     * @memberof Auction
     */
    date: number;
    /**
     * 
     * @type {string}
     * @memberof Auction
     */
    domain: string;
    /**
     * 
     * @type {string}
     * @memberof Auction
     */
    owner: string;
    /**
     * 
     * @type {number}
     * @memberof Auction
     */
    price: number;
}

/**
 * Check if a given object implements the Auction interface.
 */
export function instanceOfAuction(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "bids" in value;
    isInstance = isInstance && "date" in value;
    isInstance = isInstance && "domain" in value;
    isInstance = isInstance && "owner" in value;
    isInstance = isInstance && "price" in value;

    return isInstance;
}

export function AuctionFromJSON(json: any): Auction {
    return AuctionFromJSONTyped(json, false);
}

export function AuctionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Auction {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'bids': json['bids'],
        'date': json['date'],
        'domain': json['domain'],
        'owner': json['owner'],
        'price': json['price'],
    };
}

export function AuctionToJSON(value?: Auction | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'bids': value.bids,
        'date': value.date,
        'domain': value.domain,
        'owner': value.owner,
        'price': value.price,
    };
}

