/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@fslabs.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CurrentTime200Response
 */
export interface CurrentTime200Response {
    /**
     * 
     * @type {number}
     * @memberof CurrentTime200Response
     */
    time: number;
}

/**
 * Check if a given object implements the CurrentTime200Response interface.
 */
export function instanceOfCurrentTime200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "time" in value;

    return isInstance;
}

export function CurrentTime200ResponseFromJSON(json: any): CurrentTime200Response {
    return CurrentTime200ResponseFromJSONTyped(json, false);
}

export function CurrentTime200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CurrentTime200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'time': json['time'],
    };
}

export function CurrentTime200ResponseToJSON(value?: CurrentTime200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'time': value.time,
    };
}

