/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@fslabs.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { NftItem } from './NftItem';
import {
    NftItemFromJSON,
    NftItemFromJSONTyped,
    NftItemToJSON,
} from './NftItem';
import type { Sale } from './Sale';
import {
    SaleFromJSON,
    SaleFromJSONTyped,
    SaleToJSON,
} from './Sale';

/**
 * 
 * @export
 * @interface NftForSale
 */
export interface NftForSale {
    /**
     * 
     * @type {NftItem}
     * @memberof NftForSale
     */
    nft: NftItem;
    /**
     * 
     * @type {Sale}
     * @memberof NftForSale
     */
    sale: Sale;
    /**
     * deprecated
     * @type {string}
     * @memberof NftForSale
     */
    saleContract: string;
}

/**
 * Check if a given object implements the NftForSale interface.
 */
export function instanceOfNftForSale(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "nft" in value;
    isInstance = isInstance && "sale" in value;
    isInstance = isInstance && "saleContract" in value;

    return isInstance;
}

export function NftForSaleFromJSON(json: any): NftForSale {
    return NftForSaleFromJSONTyped(json, false);
}

export function NftForSaleFromJSONTyped(json: any, ignoreDiscriminator: boolean): NftForSale {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'nft': NftItemFromJSON(json['nft']),
        'sale': SaleFromJSON(json['sale']),
        'saleContract': json['sale_contract'],
    };
}

export function NftForSaleToJSON(value?: NftForSale | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'nft': NftItemToJSON(value.nft),
        'sale': SaleToJSON(value.sale),
        'sale_contract': value.saleContract,
    };
}

