/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@fslabs.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AccountAddress } from './AccountAddress';
import {
    AccountAddressFromJSON,
    AccountAddressFromJSONTyped,
    AccountAddressToJSON,
} from './AccountAddress';
import type { NftItemRepr } from './NftItemRepr';
import {
    NftItemReprFromJSON,
    NftItemReprFromJSONTyped,
    NftItemReprToJSON,
} from './NftItemRepr';
import type { Price } from './Price';
import {
    PriceFromJSON,
    PriceFromJSONTyped,
    PriceToJSON,
} from './Price';

/**
 * 
 * @export
 * @interface NftPurchase
 */
export interface NftPurchase {
    /**
     * 
     * @type {Price}
     * @memberof NftPurchase
     */
    amount: Price;
    /**
     * 
     * @type {AccountAddress}
     * @memberof NftPurchase
     */
    buyer: AccountAddress;
    /**
     * 
     * @type {NftItemRepr}
     * @memberof NftPurchase
     */
    nft: NftItemRepr;
    /**
     * 
     * @type {string}
     * @memberof NftPurchase
     */
    purchaseType?: NftPurchasePurchaseTypeEnum;
    /**
     * 
     * @type {AccountAddress}
     * @memberof NftPurchase
     */
    seller: AccountAddress;
}


/**
 * @export
 */
export const NftPurchasePurchaseTypeEnum = {
    DnsTg: 'DNS.tg',
    Getgems: 'getgems'
} as const;
export type NftPurchasePurchaseTypeEnum = typeof NftPurchasePurchaseTypeEnum[keyof typeof NftPurchasePurchaseTypeEnum];


/**
 * Check if a given object implements the NftPurchase interface.
 */
export function instanceOfNftPurchase(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "amount" in value;
    isInstance = isInstance && "buyer" in value;
    isInstance = isInstance && "nft" in value;
    isInstance = isInstance && "seller" in value;

    return isInstance;
}

export function NftPurchaseFromJSON(json: any): NftPurchase {
    return NftPurchaseFromJSONTyped(json, false);
}

export function NftPurchaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NftPurchase {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'amount': PriceFromJSON(json['amount']),
        'buyer': AccountAddressFromJSON(json['buyer']),
        'nft': NftItemReprFromJSON(json['nft']),
        'purchaseType': !exists(json, 'purchase_type') ? undefined : json['purchase_type'],
        'seller': AccountAddressFromJSON(json['seller']),
    };
}

export function NftPurchaseToJSON(value?: NftPurchase | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'amount': PriceToJSON(value.amount),
        'buyer': AccountAddressToJSON(value.buyer),
        'nft': NftItemReprToJSON(value.nft),
        'purchase_type': value.purchaseType,
        'seller': AccountAddressToJSON(value.seller),
    };
}

