/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@fslabs.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AccountAddress } from './AccountAddress';
import {
    AccountAddressFromJSON,
    AccountAddressFromJSONTyped,
    AccountAddressToJSON,
} from './AccountAddress';

/**
 * 
 * @export
 * @interface SubscriptionAction
 */
export interface SubscriptionAction {
    /**
     * 
     * @type {number}
     * @memberof SubscriptionAction
     */
    amount: number;
    /**
     * 
     * @type {AccountAddress}
     * @memberof SubscriptionAction
     */
    beneficiary: AccountAddress;
    /**
     * 
     * @type {boolean}
     * @memberof SubscriptionAction
     */
    initial: boolean;
    /**
     * 
     * @type {AccountAddress}
     * @memberof SubscriptionAction
     */
    subscriber: AccountAddress;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionAction
     */
    subscription: string;
}

/**
 * Check if a given object implements the SubscriptionAction interface.
 */
export function instanceOfSubscriptionAction(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "amount" in value;
    isInstance = isInstance && "beneficiary" in value;
    isInstance = isInstance && "initial" in value;
    isInstance = isInstance && "subscriber" in value;
    isInstance = isInstance && "subscription" in value;

    return isInstance;
}

export function SubscriptionActionFromJSON(json: any): SubscriptionAction {
    return SubscriptionActionFromJSONTyped(json, false);
}

export function SubscriptionActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionAction {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'beneficiary': AccountAddressFromJSON(json['beneficiary']),
        'initial': json['initial'],
        'subscriber': AccountAddressFromJSON(json['subscriber']),
        'subscription': json['subscription'],
    };
}

export function SubscriptionActionToJSON(value?: SubscriptionAction | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'amount': value.amount,
        'beneficiary': AccountAddressToJSON(value.beneficiary),
        'initial': value.initial,
        'subscriber': AccountAddressToJSON(value.subscriber),
        'subscription': value.subscription,
    };
}

