/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@fslabs.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Trace } from './Trace';
import {
    TraceFromJSON,
    TraceFromJSONTyped,
    TraceToJSON,
} from './Trace';

/**
 * 
 * @export
 * @interface Traces
 */
export interface Traces {
    /**
     * 
     * @type {Array<Trace>}
     * @memberof Traces
     */
    traces: Array<Trace>;
}

/**
 * Check if a given object implements the Traces interface.
 */
export function instanceOfTraces(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "traces" in value;

    return isInstance;
}

export function TracesFromJSON(json: any): Traces {
    return TracesFromJSONTyped(json, false);
}

export function TracesFromJSONTyped(json: any, ignoreDiscriminator: boolean): Traces {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'traces': ((json['traces'] as Array<any>).map(TraceFromJSON)),
    };
}

export function TracesToJSON(value?: Traces | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'traces': ((value.traces as Array<any>).map(TraceToJSON)),
    };
}

