/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@fslabs.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AccountAddress } from './AccountAddress';
import {
    AccountAddressFromJSON,
    AccountAddressFromJSONTyped,
    AccountAddressToJSON,
} from './AccountAddress';

/**
 * 
 * @export
 * @interface UnSubscriptionAction
 */
export interface UnSubscriptionAction {
    /**
     * 
     * @type {AccountAddress}
     * @memberof UnSubscriptionAction
     */
    beneficiary: AccountAddress;
    /**
     * 
     * @type {AccountAddress}
     * @memberof UnSubscriptionAction
     */
    subscriber: AccountAddress;
    /**
     * 
     * @type {string}
     * @memberof UnSubscriptionAction
     */
    subscription: string;
}

/**
 * Check if a given object implements the UnSubscriptionAction interface.
 */
export function instanceOfUnSubscriptionAction(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "beneficiary" in value;
    isInstance = isInstance && "subscriber" in value;
    isInstance = isInstance && "subscription" in value;

    return isInstance;
}

export function UnSubscriptionActionFromJSON(json: any): UnSubscriptionAction {
    return UnSubscriptionActionFromJSONTyped(json, false);
}

export function UnSubscriptionActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnSubscriptionAction {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'beneficiary': AccountAddressFromJSON(json['beneficiary']),
        'subscriber': AccountAddressFromJSON(json['subscriber']),
        'subscription': json['subscription'],
    };
}

export function UnSubscriptionActionToJSON(value?: UnSubscriptionAction | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'beneficiary': AccountAddressToJSON(value.beneficiary),
        'subscriber': AccountAddressToJSON(value.subscriber),
        'subscription': value.subscription,
    };
}

