/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@fslabs.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Validator
 */
export interface Validator {
    /**
     * 
     * @type {string}
     * @memberof Validator
     */
    address: string;
    /**
     * 
     * @type {string}
     * @memberof Validator
     */
    adnlAddress: string;
    /**
     * 
     * @type {number}
     * @memberof Validator
     */
    maxFactor: number;
    /**
     * 
     * @type {number}
     * @memberof Validator
     */
    stake: number;
}

/**
 * Check if a given object implements the Validator interface.
 */
export function instanceOfValidator(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "address" in value;
    isInstance = isInstance && "adnlAddress" in value;
    isInstance = isInstance && "maxFactor" in value;
    isInstance = isInstance && "stake" in value;

    return isInstance;
}

export function ValidatorFromJSON(json: any): Validator {
    return ValidatorFromJSONTyped(json, false);
}

export function ValidatorFromJSONTyped(json: any, ignoreDiscriminator: boolean): Validator {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'address': json['address'],
        'adnlAddress': json['adnlAddress'],
        'maxFactor': json['maxFactor'],
        'stake': json['stake'],
    };
}

export function ValidatorToJSON(value?: Validator | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'address': value.address,
        'adnlAddress': value.adnlAddress,
        'maxFactor': value.maxFactor,
        'stake': value.stake,
    };
}

