/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@fslabs.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Wallet } from './Wallet';
import {
    WalletFromJSON,
    WalletFromJSONTyped,
    WalletToJSON,
} from './Wallet';

/**
 * 
 * @export
 * @interface Wallets
 */
export interface Wallets {
    /**
     * 
     * @type {Array<Wallet>}
     * @memberof Wallets
     */
    wallets: Array<Wallet>;
}

/**
 * Check if a given object implements the Wallets interface.
 */
export function instanceOfWallets(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "wallets" in value;

    return isInstance;
}

export function WalletsFromJSON(json: any): Wallets {
    return WalletsFromJSONTyped(json, false);
}

export function WalletsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Wallets {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'wallets': ((json['wallets'] as Array<any>).map(WalletFromJSON)),
    };
}

export function WalletsToJSON(value?: Wallets | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'wallets': ((value.wallets as Array<any>).map(WalletToJSON)),
    };
}

