/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AccountStatus = {
    Nonexist: 'nonexist',
    Uninit: 'uninit',
    Active: 'active',
    Frozen: 'frozen'
} as const;
export type AccountStatus = typeof AccountStatus[keyof typeof AccountStatus];


export function AccountStatusFromJSON(json: any): AccountStatus {
    return AccountStatusFromJSONTyped(json, false);
}

export function AccountStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountStatus {
    return json as AccountStatus;
}

export function AccountStatusToJSON(value?: AccountStatus | null): any {
    return value as any;
}

