/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ActionPhase
 */
export interface ActionPhase {
    /**
     * 
     * @type {boolean}
     * @memberof ActionPhase
     */
    success: boolean;
    /**
     * 
     * @type {number}
     * @memberof ActionPhase
     */
    totalActions: number;
    /**
     * 
     * @type {number}
     * @memberof ActionPhase
     */
    skippedActions: number;
    /**
     * 
     * @type {number}
     * @memberof ActionPhase
     */
    fwdFees: number;
    /**
     * 
     * @type {number}
     * @memberof ActionPhase
     */
    totalFees: number;
}

/**
 * Check if a given object implements the ActionPhase interface.
 */
export function instanceOfActionPhase(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "success" in value;
    isInstance = isInstance && "totalActions" in value;
    isInstance = isInstance && "skippedActions" in value;
    isInstance = isInstance && "fwdFees" in value;
    isInstance = isInstance && "totalFees" in value;

    return isInstance;
}

export function ActionPhaseFromJSON(json: any): ActionPhase {
    return ActionPhaseFromJSONTyped(json, false);
}

export function ActionPhaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActionPhase {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': json['success'],
        'totalActions': json['total_actions'],
        'skippedActions': json['skipped_actions'],
        'fwdFees': json['fwd_fees'],
        'totalFees': json['total_fees'],
    };
}

export function ActionPhaseToJSON(value?: ActionPhase | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'total_actions': value.totalActions,
        'skipped_actions': value.skippedActions,
        'fwd_fees': value.fwdFees,
        'total_fees': value.totalFees,
    };
}

