/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContractDeployAction
 */
export interface ContractDeployAction {
    /**
     * 
     * @type {string}
     * @memberof ContractDeployAction
     */
    address: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ContractDeployAction
     */
    interfaces: Array<string>;
}

/**
 * Check if a given object implements the ContractDeployAction interface.
 */
export function instanceOfContractDeployAction(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "address" in value;
    isInstance = isInstance && "interfaces" in value;

    return isInstance;
}

export function ContractDeployActionFromJSON(json: any): ContractDeployAction {
    return ContractDeployActionFromJSONTyped(json, false);
}

export function ContractDeployActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContractDeployAction {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'address': json['address'],
        'interfaces': json['interfaces'],
    };
}

export function ContractDeployActionToJSON(value?: ContractDeployAction | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'address': value.address,
        'interfaces': value.interfaces,
    };
}

