/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreditPhase
 */
export interface CreditPhase {
    /**
     * 
     * @type {number}
     * @memberof CreditPhase
     */
    feesCollected: number;
    /**
     * 
     * @type {number}
     * @memberof CreditPhase
     */
    credit: number;
}

/**
 * Check if a given object implements the CreditPhase interface.
 */
export function instanceOfCreditPhase(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "feesCollected" in value;
    isInstance = isInstance && "credit" in value;

    return isInstance;
}

export function CreditPhaseFromJSON(json: any): CreditPhase {
    return CreditPhaseFromJSONTyped(json, false);
}

export function CreditPhaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreditPhase {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'feesCollected': json['fees_collected'],
        'credit': json['credit'],
    };
}

export function CreditPhaseToJSON(value?: CreditPhase | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'fees_collected': value.feesCollected,
        'credit': value.credit,
    };
}

