/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { FoundAccountsAddressesInner } from './FoundAccountsAddressesInner';
import {
    FoundAccountsAddressesInnerFromJSON,
    FoundAccountsAddressesInnerFromJSONTyped,
    FoundAccountsAddressesInnerToJSON,
} from './FoundAccountsAddressesInner';

/**
 * 
 * @export
 * @interface FoundAccounts
 */
export interface FoundAccounts {
    /**
     * 
     * @type {Array<FoundAccountsAddressesInner>}
     * @memberof FoundAccounts
     */
    addresses: Array<FoundAccountsAddressesInner>;
}

/**
 * Check if a given object implements the FoundAccounts interface.
 */
export function instanceOfFoundAccounts(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "addresses" in value;

    return isInstance;
}

export function FoundAccountsFromJSON(json: any): FoundAccounts {
    return FoundAccountsFromJSONTyped(json, false);
}

export function FoundAccountsFromJSONTyped(json: any, ignoreDiscriminator: boolean): FoundAccounts {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'addresses': ((json['addresses'] as Array<any>).map(FoundAccountsAddressesInnerFromJSON)),
    };
}

export function FoundAccountsToJSON(value?: FoundAccounts | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'addresses': ((value.addresses as Array<any>).map(FoundAccountsAddressesInnerToJSON)),
    };
}

