/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetAccountsRequest
 */
export interface GetAccountsRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof GetAccountsRequest
     */
    accountIds: Array<string>;
}

/**
 * Check if a given object implements the GetAccountsRequest interface.
 */
export function instanceOfGetAccountsRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "accountIds" in value;

    return isInstance;
}

export function GetAccountsRequestFromJSON(json: any): GetAccountsRequest {
    return GetAccountsRequestFromJSONTyped(json, false);
}

export function GetAccountsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAccountsRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accountIds': json['account_ids'],
    };
}

export function GetAccountsRequestToJSON(value?: GetAccountsRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'account_ids': value.accountIds,
    };
}

