/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BlockRaw } from './BlockRaw';
import {
    BlockRawFromJSON,
    BlockRawFromJSONTyped,
    BlockRawToJSON,
} from './BlockRaw';
import type { GetBlockProofLiteServer200ResponseStepsInnerLiteServerBlockLinkForwardSignatures } from './GetBlockProofLiteServer200ResponseStepsInnerLiteServerBlockLinkForwardSignatures';
import {
    GetBlockProofLiteServer200ResponseStepsInnerLiteServerBlockLinkForwardSignaturesFromJSON,
    GetBlockProofLiteServer200ResponseStepsInnerLiteServerBlockLinkForwardSignaturesFromJSONTyped,
    GetBlockProofLiteServer200ResponseStepsInnerLiteServerBlockLinkForwardSignaturesToJSON,
} from './GetBlockProofLiteServer200ResponseStepsInnerLiteServerBlockLinkForwardSignatures';

/**
 * 
 * @export
 * @interface GetBlockProofLiteServer200ResponseStepsInnerLiteServerBlockLinkForward
 */
export interface GetBlockProofLiteServer200ResponseStepsInnerLiteServerBlockLinkForward {
    /**
     * 
     * @type {boolean}
     * @memberof GetBlockProofLiteServer200ResponseStepsInnerLiteServerBlockLinkForward
     */
    toKeyBlock: boolean;
    /**
     * 
     * @type {BlockRaw}
     * @memberof GetBlockProofLiteServer200ResponseStepsInnerLiteServerBlockLinkForward
     */
    from: BlockRaw;
    /**
     * 
     * @type {BlockRaw}
     * @memberof GetBlockProofLiteServer200ResponseStepsInnerLiteServerBlockLinkForward
     */
    to: BlockRaw;
    /**
     * 
     * @type {string}
     * @memberof GetBlockProofLiteServer200ResponseStepsInnerLiteServerBlockLinkForward
     */
    destProof: string;
    /**
     * 
     * @type {string}
     * @memberof GetBlockProofLiteServer200ResponseStepsInnerLiteServerBlockLinkForward
     */
    configProof: string;
    /**
     * 
     * @type {GetBlockProofLiteServer200ResponseStepsInnerLiteServerBlockLinkForwardSignatures}
     * @memberof GetBlockProofLiteServer200ResponseStepsInnerLiteServerBlockLinkForward
     */
    signatures: GetBlockProofLiteServer200ResponseStepsInnerLiteServerBlockLinkForwardSignatures;
}

/**
 * Check if a given object implements the GetBlockProofLiteServer200ResponseStepsInnerLiteServerBlockLinkForward interface.
 */
export function instanceOfGetBlockProofLiteServer200ResponseStepsInnerLiteServerBlockLinkForward(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "toKeyBlock" in value;
    isInstance = isInstance && "from" in value;
    isInstance = isInstance && "to" in value;
    isInstance = isInstance && "destProof" in value;
    isInstance = isInstance && "configProof" in value;
    isInstance = isInstance && "signatures" in value;

    return isInstance;
}

export function GetBlockProofLiteServer200ResponseStepsInnerLiteServerBlockLinkForwardFromJSON(json: any): GetBlockProofLiteServer200ResponseStepsInnerLiteServerBlockLinkForward {
    return GetBlockProofLiteServer200ResponseStepsInnerLiteServerBlockLinkForwardFromJSONTyped(json, false);
}

export function GetBlockProofLiteServer200ResponseStepsInnerLiteServerBlockLinkForwardFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetBlockProofLiteServer200ResponseStepsInnerLiteServerBlockLinkForward {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'toKeyBlock': json['to_key_block'],
        'from': BlockRawFromJSON(json['from']),
        'to': BlockRawFromJSON(json['to']),
        'destProof': json['dest_proof'],
        'configProof': json['config_proof'],
        'signatures': GetBlockProofLiteServer200ResponseStepsInnerLiteServerBlockLinkForwardSignaturesFromJSON(json['signatures']),
    };
}

export function GetBlockProofLiteServer200ResponseStepsInnerLiteServerBlockLinkForwardToJSON(value?: GetBlockProofLiteServer200ResponseStepsInnerLiteServerBlockLinkForward | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'to_key_block': value.toKeyBlock,
        'from': BlockRawToJSON(value.from),
        'to': BlockRawToJSON(value.to),
        'dest_proof': value.destProof,
        'config_proof': value.configProof,
        'signatures': GetBlockProofLiteServer200ResponseStepsInnerLiteServerBlockLinkForwardSignaturesToJSON(value.signatures),
    };
}

