/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetBlockDefaultResponse
 */
export interface GetBlockDefaultResponse {
    /**
     * 
     * @type {string}
     * @memberof GetBlockDefaultResponse
     */
    error: string;
}

/**
 * Check if a given object implements the GetBlockDefaultResponse interface.
 */
export function instanceOfGetBlockDefaultResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "error" in value;

    return isInstance;
}

export function GetBlockDefaultResponseFromJSON(json: any): GetBlockDefaultResponse {
    return GetBlockDefaultResponseFromJSONTyped(json, false);
}

export function GetBlockDefaultResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetBlockDefaultResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'error': json['error'],
    };
}

export function GetBlockDefaultResponseToJSON(value?: GetBlockDefaultResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'error': value.error,
    };
}

