/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetBlockProofLiteServer200ResponseStepsInnerLiteServerBlockLinkBack } from './GetBlockProofLiteServer200ResponseStepsInnerLiteServerBlockLinkBack';
import {
    GetBlockProofLiteServer200ResponseStepsInnerLiteServerBlockLinkBackFromJSON,
    GetBlockProofLiteServer200ResponseStepsInnerLiteServerBlockLinkBackFromJSONTyped,
    GetBlockProofLiteServer200ResponseStepsInnerLiteServerBlockLinkBackToJSON,
} from './GetBlockProofLiteServer200ResponseStepsInnerLiteServerBlockLinkBack';
import type { GetBlockProofLiteServer200ResponseStepsInnerLiteServerBlockLinkForward } from './GetBlockProofLiteServer200ResponseStepsInnerLiteServerBlockLinkForward';
import {
    GetBlockProofLiteServer200ResponseStepsInnerLiteServerBlockLinkForwardFromJSON,
    GetBlockProofLiteServer200ResponseStepsInnerLiteServerBlockLinkForwardFromJSONTyped,
    GetBlockProofLiteServer200ResponseStepsInnerLiteServerBlockLinkForwardToJSON,
} from './GetBlockProofLiteServer200ResponseStepsInnerLiteServerBlockLinkForward';

/**
 * 
 * @export
 * @interface GetBlockProofLiteServer200ResponseStepsInner
 */
export interface GetBlockProofLiteServer200ResponseStepsInner {
    /**
     * 
     * @type {GetBlockProofLiteServer200ResponseStepsInnerLiteServerBlockLinkBack}
     * @memberof GetBlockProofLiteServer200ResponseStepsInner
     */
    liteServerBlockLinkBack: GetBlockProofLiteServer200ResponseStepsInnerLiteServerBlockLinkBack;
    /**
     * 
     * @type {GetBlockProofLiteServer200ResponseStepsInnerLiteServerBlockLinkForward}
     * @memberof GetBlockProofLiteServer200ResponseStepsInner
     */
    liteServerBlockLinkForward: GetBlockProofLiteServer200ResponseStepsInnerLiteServerBlockLinkForward;
}

/**
 * Check if a given object implements the GetBlockProofLiteServer200ResponseStepsInner interface.
 */
export function instanceOfGetBlockProofLiteServer200ResponseStepsInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "liteServerBlockLinkBack" in value;
    isInstance = isInstance && "liteServerBlockLinkForward" in value;

    return isInstance;
}

export function GetBlockProofLiteServer200ResponseStepsInnerFromJSON(json: any): GetBlockProofLiteServer200ResponseStepsInner {
    return GetBlockProofLiteServer200ResponseStepsInnerFromJSONTyped(json, false);
}

export function GetBlockProofLiteServer200ResponseStepsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetBlockProofLiteServer200ResponseStepsInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'liteServerBlockLinkBack': GetBlockProofLiteServer200ResponseStepsInnerLiteServerBlockLinkBackFromJSON(json['lite_server_block_link_back']),
        'liteServerBlockLinkForward': GetBlockProofLiteServer200ResponseStepsInnerLiteServerBlockLinkForwardFromJSON(json['lite_server_block_link_forward']),
    };
}

export function GetBlockProofLiteServer200ResponseStepsInnerToJSON(value?: GetBlockProofLiteServer200ResponseStepsInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'lite_server_block_link_back': GetBlockProofLiteServer200ResponseStepsInnerLiteServerBlockLinkBackToJSON(value.liteServerBlockLinkBack),
        'lite_server_block_link_forward': GetBlockProofLiteServer200ResponseStepsInnerLiteServerBlockLinkForwardToJSON(value.liteServerBlockLinkForward),
    };
}

