/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetListBlockTransactionsLiteServer200ResponseIdsInner
 */
export interface GetListBlockTransactionsLiteServer200ResponseIdsInner {
    /**
     * 
     * @type {number}
     * @memberof GetListBlockTransactionsLiteServer200ResponseIdsInner
     */
    mode: number;
    /**
     * 
     * @type {string}
     * @memberof GetListBlockTransactionsLiteServer200ResponseIdsInner
     */
    account?: string;
    /**
     * 
     * @type {number}
     * @memberof GetListBlockTransactionsLiteServer200ResponseIdsInner
     */
    lt?: number;
    /**
     * 
     * @type {string}
     * @memberof GetListBlockTransactionsLiteServer200ResponseIdsInner
     */
    hash?: string;
}

/**
 * Check if a given object implements the GetListBlockTransactionsLiteServer200ResponseIdsInner interface.
 */
export function instanceOfGetListBlockTransactionsLiteServer200ResponseIdsInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "mode" in value;

    return isInstance;
}

export function GetListBlockTransactionsLiteServer200ResponseIdsInnerFromJSON(json: any): GetListBlockTransactionsLiteServer200ResponseIdsInner {
    return GetListBlockTransactionsLiteServer200ResponseIdsInnerFromJSONTyped(json, false);
}

export function GetListBlockTransactionsLiteServer200ResponseIdsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetListBlockTransactionsLiteServer200ResponseIdsInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'mode': json['mode'],
        'account': !exists(json, 'account') ? undefined : json['account'],
        'lt': !exists(json, 'lt') ? undefined : json['lt'],
        'hash': !exists(json, 'hash') ? undefined : json['hash'],
    };
}

export function GetListBlockTransactionsLiteServer200ResponseIdsInnerToJSON(value?: GetListBlockTransactionsLiteServer200ResponseIdsInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'mode': value.mode,
        'account': value.account,
        'lt': value.lt,
        'hash': value.hash,
    };
}

