/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BlockRaw } from './BlockRaw';
import {
    BlockRawFromJSON,
    BlockRawFromJSONTyped,
    BlockRawToJSON,
} from './BlockRaw';
import type { InitStateRaw } from './InitStateRaw';
import {
    InitStateRawFromJSON,
    InitStateRawFromJSONTyped,
    InitStateRawToJSON,
} from './InitStateRaw';

/**
 * 
 * @export
 * @interface GetMasterchainInfoLiteServer200Response
 */
export interface GetMasterchainInfoLiteServer200Response {
    /**
     * 
     * @type {BlockRaw}
     * @memberof GetMasterchainInfoLiteServer200Response
     */
    last: BlockRaw;
    /**
     * 
     * @type {string}
     * @memberof GetMasterchainInfoLiteServer200Response
     */
    stateRootHash: string;
    /**
     * 
     * @type {InitStateRaw}
     * @memberof GetMasterchainInfoLiteServer200Response
     */
    init: InitStateRaw;
}

/**
 * Check if a given object implements the GetMasterchainInfoLiteServer200Response interface.
 */
export function instanceOfGetMasterchainInfoLiteServer200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "last" in value;
    isInstance = isInstance && "stateRootHash" in value;
    isInstance = isInstance && "init" in value;

    return isInstance;
}

export function GetMasterchainInfoLiteServer200ResponseFromJSON(json: any): GetMasterchainInfoLiteServer200Response {
    return GetMasterchainInfoLiteServer200ResponseFromJSONTyped(json, false);
}

export function GetMasterchainInfoLiteServer200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetMasterchainInfoLiteServer200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'last': BlockRawFromJSON(json['last']),
        'stateRootHash': json['state_root_hash'],
        'init': InitStateRawFromJSON(json['init']),
    };
}

export function GetMasterchainInfoLiteServer200ResponseToJSON(value?: GetMasterchainInfoLiteServer200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'last': BlockRawToJSON(value.last),
        'state_root_hash': value.stateRootHash,
        'init': InitStateRawToJSON(value.init),
    };
}

