/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetRates200Response
 */
export interface GetRates200Response {
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof GetRates200Response
     */
    rates: { [key: string]: any; };
}

/**
 * Check if a given object implements the GetRates200Response interface.
 */
export function instanceOfGetRates200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "rates" in value;

    return isInstance;
}

export function GetRates200ResponseFromJSON(json: any): GetRates200Response {
    return GetRates200ResponseFromJSONTyped(json, false);
}

export function GetRates200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetRates200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'rates': json['rates'],
    };
}

export function GetRates200ResponseToJSON(value?: GetRates200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'rates': value.rates,
    };
}

