/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BlockRaw } from './BlockRaw';
import {
    BlockRawFromJSON,
    BlockRawFromJSONTyped,
    BlockRawToJSON,
} from './BlockRaw';

/**
 * 
 * @export
 * @interface GetStateLiteServer200Response
 */
export interface GetStateLiteServer200Response {
    /**
     * 
     * @type {BlockRaw}
     * @memberof GetStateLiteServer200Response
     */
    id: BlockRaw;
    /**
     * 
     * @type {string}
     * @memberof GetStateLiteServer200Response
     */
    rootHash: string;
    /**
     * 
     * @type {string}
     * @memberof GetStateLiteServer200Response
     */
    fileHash: string;
    /**
     * 
     * @type {string}
     * @memberof GetStateLiteServer200Response
     */
    data: string;
}

/**
 * Check if a given object implements the GetStateLiteServer200Response interface.
 */
export function instanceOfGetStateLiteServer200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "rootHash" in value;
    isInstance = isInstance && "fileHash" in value;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function GetStateLiteServer200ResponseFromJSON(json: any): GetStateLiteServer200Response {
    return GetStateLiteServer200ResponseFromJSONTyped(json, false);
}

export function GetStateLiteServer200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetStateLiteServer200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': BlockRawFromJSON(json['id']),
        'rootHash': json['root_hash'],
        'fileHash': json['file_hash'],
        'data': json['data'],
    };
}

export function GetStateLiteServer200ResponseToJSON(value?: GetStateLiteServer200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': BlockRawToJSON(value.id),
        'root_hash': value.rootHash,
        'file_hash': value.fileHash,
        'data': value.data,
    };
}

