/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetTimeLiteServer200Response
 */
export interface GetTimeLiteServer200Response {
    /**
     * 
     * @type {number}
     * @memberof GetTimeLiteServer200Response
     */
    time: number;
}

/**
 * Check if a given object implements the GetTimeLiteServer200Response interface.
 */
export function instanceOfGetTimeLiteServer200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "time" in value;

    return isInstance;
}

export function GetTimeLiteServer200ResponseFromJSON(json: any): GetTimeLiteServer200Response {
    return GetTimeLiteServer200ResponseFromJSONTyped(json, false);
}

export function GetTimeLiteServer200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetTimeLiteServer200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'time': json['time'],
    };
}

export function GetTimeLiteServer200ResponseToJSON(value?: GetTimeLiteServer200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'time': value.time,
    };
}

