/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AccountAddress } from './AccountAddress';
import {
    AccountAddressFromJSON,
    AccountAddressFromJSONTyped,
    AccountAddressToJSON,
} from './AccountAddress';
import type { EncryptedComment } from './EncryptedComment';
import {
    EncryptedCommentFromJSON,
    EncryptedCommentFromJSONTyped,
    EncryptedCommentToJSON,
} from './EncryptedComment';
import type { JettonPreview } from './JettonPreview';
import {
    JettonPreviewFromJSON,
    JettonPreviewFromJSONTyped,
    JettonPreviewToJSON,
} from './JettonPreview';
import type { Refund } from './Refund';
import {
    RefundFromJSON,
    RefundFromJSONTyped,
    RefundToJSON,
} from './Refund';

/**
 * 
 * @export
 * @interface JettonTransferAction
 */
export interface JettonTransferAction {
    /**
     * 
     * @type {AccountAddress}
     * @memberof JettonTransferAction
     */
    sender?: AccountAddress;
    /**
     * 
     * @type {AccountAddress}
     * @memberof JettonTransferAction
     */
    recipient?: AccountAddress;
    /**
     * 
     * @type {string}
     * @memberof JettonTransferAction
     */
    sendersWallet: string;
    /**
     * 
     * @type {string}
     * @memberof JettonTransferAction
     */
    recipientsWallet: string;
    /**
     * amount in quanta of tokens
     * @type {string}
     * @memberof JettonTransferAction
     */
    amount: string;
    /**
     * 
     * @type {string}
     * @memberof JettonTransferAction
     */
    comment?: string;
    /**
     * 
     * @type {EncryptedComment}
     * @memberof JettonTransferAction
     */
    encryptedComment?: EncryptedComment;
    /**
     * 
     * @type {Refund}
     * @memberof JettonTransferAction
     */
    refund?: Refund;
    /**
     * 
     * @type {JettonPreview}
     * @memberof JettonTransferAction
     */
    jetton: JettonPreview;
}

/**
 * Check if a given object implements the JettonTransferAction interface.
 */
export function instanceOfJettonTransferAction(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "sendersWallet" in value;
    isInstance = isInstance && "recipientsWallet" in value;
    isInstance = isInstance && "amount" in value;
    isInstance = isInstance && "jetton" in value;

    return isInstance;
}

export function JettonTransferActionFromJSON(json: any): JettonTransferAction {
    return JettonTransferActionFromJSONTyped(json, false);
}

export function JettonTransferActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): JettonTransferAction {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'sender': !exists(json, 'sender') ? undefined : AccountAddressFromJSON(json['sender']),
        'recipient': !exists(json, 'recipient') ? undefined : AccountAddressFromJSON(json['recipient']),
        'sendersWallet': json['senders_wallet'],
        'recipientsWallet': json['recipients_wallet'],
        'amount': json['amount'],
        'comment': !exists(json, 'comment') ? undefined : json['comment'],
        'encryptedComment': !exists(json, 'encrypted_comment') ? undefined : EncryptedCommentFromJSON(json['encrypted_comment']),
        'refund': !exists(json, 'refund') ? undefined : RefundFromJSON(json['refund']),
        'jetton': JettonPreviewFromJSON(json['jetton']),
    };
}

export function JettonTransferActionToJSON(value?: JettonTransferAction | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'sender': AccountAddressToJSON(value.sender),
        'recipient': AccountAddressToJSON(value.recipient),
        'senders_wallet': value.sendersWallet,
        'recipients_wallet': value.recipientsWallet,
        'amount': value.amount,
        'comment': value.comment,
        'encrypted_comment': EncryptedCommentToJSON(value.encryptedComment),
        'refund': RefundToJSON(value.refund),
        'jetton': JettonPreviewToJSON(value.jetton),
    };
}

