/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AccountAddress } from './AccountAddress';
import {
    AccountAddressFromJSON,
    AccountAddressFromJSONTyped,
    AccountAddressToJSON,
} from './AccountAddress';
import type { JettonPreview } from './JettonPreview';
import {
    JettonPreviewFromJSON,
    JettonPreviewFromJSONTyped,
    JettonPreviewToJSON,
} from './JettonPreview';

/**
 * 
 * @export
 * @interface JettonBalance
 */
export interface JettonBalance {
    /**
     * 
     * @type {string}
     * @memberof JettonBalance
     */
    balance: string;
    /**
     * 
     * @type {AccountAddress}
     * @memberof JettonBalance
     */
    walletAddress: AccountAddress;
    /**
     * 
     * @type {JettonPreview}
     * @memberof JettonBalance
     */
    jetton: JettonPreview;
}

/**
 * Check if a given object implements the JettonBalance interface.
 */
export function instanceOfJettonBalance(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "balance" in value;
    isInstance = isInstance && "walletAddress" in value;
    isInstance = isInstance && "jetton" in value;

    return isInstance;
}

export function JettonBalanceFromJSON(json: any): JettonBalance {
    return JettonBalanceFromJSONTyped(json, false);
}

export function JettonBalanceFromJSONTyped(json: any, ignoreDiscriminator: boolean): JettonBalance {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'balance': json['balance'],
        'walletAddress': AccountAddressFromJSON(json['wallet_address']),
        'jetton': JettonPreviewFromJSON(json['jetton']),
    };
}

export function JettonBalanceToJSON(value?: JettonBalance | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'balance': value.balance,
        'wallet_address': AccountAddressToJSON(value.walletAddress),
        'jetton': JettonPreviewToJSON(value.jetton),
    };
}

