/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NftItemCollection
 */
export interface NftItemCollection {
    /**
     * 
     * @type {string}
     * @memberof NftItemCollection
     */
    address: string;
    /**
     * 
     * @type {string}
     * @memberof NftItemCollection
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof NftItemCollection
     */
    description: string;
}

/**
 * Check if a given object implements the NftItemCollection interface.
 */
export function instanceOfNftItemCollection(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "address" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "description" in value;

    return isInstance;
}

export function NftItemCollectionFromJSON(json: any): NftItemCollection {
    return NftItemCollectionFromJSONTyped(json, false);
}

export function NftItemCollectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): NftItemCollection {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'address': json['address'],
        'name': json['name'],
        'description': json['description'],
    };
}

export function NftItemCollectionToJSON(value?: NftItemCollection | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'address': value.address,
        'name': value.name,
        'description': value.description,
    };
}

