/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SendMessageLiteServerRequest
 */
export interface SendMessageLiteServerRequest {
    /**
     * 
     * @type {string}
     * @memberof SendMessageLiteServerRequest
     */
    body: string;
}

/**
 * Check if a given object implements the SendMessageLiteServerRequest interface.
 */
export function instanceOfSendMessageLiteServerRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "body" in value;

    return isInstance;
}

export function SendMessageLiteServerRequestFromJSON(json: any): SendMessageLiteServerRequest {
    return SendMessageLiteServerRequestFromJSONTyped(json, false);
}

export function SendMessageLiteServerRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendMessageLiteServerRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'body': json['body'],
    };
}

export function SendMessageLiteServerRequestToJSON(value?: SendMessageLiteServerRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'body': value.body,
    };
}

